apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - playground-pvc.yaml
  - playground-deployment.yaml
  - playground-service.yaml
  - playground-pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/name: playground
    includeSelectors: true
